### ISSUE TITLE
CurrentRegion auto detect

### ISSUE THREAD

**Issue by davidflury** [saycle/saycle#15]
Enable automatic region detection to set the language when the page is loaded.
Proof concept to save the language of a logged in user in the user-table in the database.

Hints: i18n and angular-translate
Code: /viewmodels/saycle.js

**Comment by sebibrunner** [comment]
set the "default"-language per javascript: 
navigator.languages[0] || navigator.language || navigator.userLanguage
each browser will handle the languages different, p.E. Edge shows de-CH per default, while chrome does not. Swiss german will probably be a problem...

**Comment by davidflury** [comment]
JUST DO IT!
Set a cookie so the last language is saved for a user.

**Comment by davidflury** [comment]
Fixed in feature-branch with commit 5a0a5c916d28a0cde94f5df0a0864ff62f296a9e
